
build-kvmtool:
  stage: build
  image: gcc:8
  script:
    - git clone https://git.kernel.org/pub/scm/linux/kernel/git/will/kvmtool.git
    - cd kvmtool && make -j$(nproc)
  artifacts:
    untracked: false
    paths:
      - kvmtool/vm
    expire_in: 30 days

build-tests:
  stage: build
  image: golang:1.11
  script:
    - cd ioctl && go test -c
  artifacts:
    untracked: false
    paths:
      - ioctl/ioctl.test
    expire_in: 30 days

test:
  stage: test
  image: debian:stretch
  variables:
    NEEDS_KVM: "true"
  dependencies:
    - build-kvmtool
    - build-tests
  script:
    - apt-get update && apt-get -yy install wget
    - wget -O bzImage https://blob.dolansoft.org/public/gozfs-testenv-linux
    - kvmtool/vm run -m 256m --kernel bzImage -c1 --console virtio -d ioctl -p "init=/ioctl.test"
